version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: clockwork-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: clockwork-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    container_name: clockwork-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: